---
- name: Enable forward policy
  ansible.builtin.lineinfile:
    path: /etc/default/ufw
    regexp: '^DEFAULT_FORWARD_POLICY'
    line: 'DEFAULT_FORWARD_POLICY="ACCEPT"'
  become: yes
  notify:
    - restart ufw

- name: Enable ip forward
  ansible.builtin.lineinfile:
    path: /etc/ufw/sysctl.conf
    regexp: "{{ 'net/ipv4/ip_forward' | regex_escape() }}"
    line: "net/ipv4/ip_forward=1"
  become: yes
  notify:
    - restart ufw

- name: Enable localnet route
  ansible.builtin.lineinfile:
    path: /etc/ufw/sysctl.conf
    regexp: "{{ 'net/ipv4/conf/' + ufw_forward_interface + '/route_localnet' | regex_escape() }}"
    line: "net/ipv4/conf/{{ ufw_forward_interface }}/route_localnet=1"
  become: yes
  notify:
    - restart ufw

- name: Setup port forwards and masq
  ansible.builtin.template:
    src: templates/before.rules.j2
    dest: /etc/ufw/before.rules
    owner: root
    group: root
    mode: '0640'
  become: yes
  notify:
    - restart ufw
